### Exercise 2a: find the even values in this numpy array

Use indexing to find all the values in the array that are even. Don't use a for-loop!

* Hint 1: Have a look at how the array is made. It uses np.arange, a very useful function. np.arange(start, stop, step) makes an ndarray starting at 'start', stopping at 'stop' (non-inclusive) with a step of 'step'. 
* Hint 2: Remember an even value is value % 2 == 0

In [7]:
import numpy as np
array = np.arange(0,10,1) 
answer = array[array % 2 == 0]
print(answer)

[0 2 4 6 8]


### Exercise 2b: replace values below threshold with 0
This is a repeat of exercise 1e, but now we're going to use a numpy array and indexing to write the answer in just 1 line. 

* Tip 1: Don't make a new array, you can just replace the values in 'myarray'

In [10]:
myarray = np.array([1,2,9,3,2,8,3,3,11,2])
threshold = 5
myarray[myarray < threshold] = 0
print(myarray)

[ 0  0  9  0  0  8  0  0 11  0]


### Exercise 2c: find the positions
Find the positions in the array where the array is exactly 3.

* Hint 1: You will need to use the function np.where. Find out more about the function in the documentation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html


In [27]:
myarray = np.array([1,2,9,3,2,8,3,3,11,2])
answer = np.where(myarray == 3)[0]

### Exercise 2d: Find mean, median and standard deviation
Find the mean, median and standard deviation of the array. Use a numpy function for this

* Hint 1: Try to google 'numpy mean' to find the documentation for the function

In [28]:
myarray = np.array([1,2,9,3,2,8,3,3,11,2])
print('mean: ', np.mean(myarray))
print('median: ', np.median(myarray))
print('std: ', np.std(myarray))

mean:  4.4
median:  3.0
std:  3.352610922848042


### Exercise 2e: Find mean, median and standard deviation of each row
Find the mean, median and standard deviation of each row in the array. Use the same numpy function as above, but you need to add the axis parameter. Read through the documentation or use the help function if you're not sure how to use it.


In [29]:
myarray = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print('mean: ', np.mean(myarray,  axis=1))
print('median: ', np.median(myarray,  axis=1))
print('std: ', np.std(myarray,  axis=1))

mean:  [2. 5. 8.]
median:  [2. 5. 8.]
std:  [0.81649658 0.81649658 0.81649658]


### Exercise 2f: Time spent in quadrants
This array contains  the quadrant a mouse was in at each time point (in seconds). Find the total time (i.e. how often that number appears in the array) for each quadrant.

* Hint 1: You can do this either using indexing (like above) or using the 'unique' function (https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html)
* Hint 2: Have a look at how the quadrants variable was made and see if you can figure out how to make a quadrants array with 200 values from 1 to 6.

In [35]:
quadrants = np.random.choice([1,2,3,4],100)
u, count = np.unique(quadrants,return_counts=True)
print(count)

#Alternative:
counts = []
for i in range(1,5):
    count = len(quadrants[quadrants==i])
    counts.append(count)
counts

[19 27 28 26]


[19, 27, 28, 26]

### Exercise 2g: cumulative distance in numpy
Write a function to find the cumulative distance of a list of x,y coordinates. However, this time we are going to use a numpy array and you need to use a scipy function to calculate the distance. 

* Hint 1: Scipy distance has already been imported for you, which means that now you can use the distance functions. You will need to use distance.euclidean (more info here https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.distance.euclidean.html)

In [1]:
from scipy.spatial import distance
coordinates = np.array(
              [[1,2],
               [1,3],
               [2,3],
               [3,4],
               [4,4]])

cumsum = [0]
for i,coors in enumerate(coordinates[:-1]):
    d = distance.euclidean(coors, coordinates[i+1])
    cumsum.append(cumsum[i]+d)

NameError: name 'np' is not defined

### Exercise 2h: load data into a numpy array
In the folder 'data' you find a csv-file called 'loco'. You can load data like this into numpy using the function 'genfromtxt' (https://numpy.org/devdocs/user/basics.io.genfromtxt.html). Try to load the data and find the maximum location in the array. 

* Hint 1: Open the file to check out what the data looks like. 
* Hint 2: You want to skip the header, the delimiter is ',' and you will only need the second column. You can set all of these things using the parameters in the genfromtxt function


In [16]:
import os
datafile = os.path.join('data', 'loco.csv')

data = np.genfromtxt(datafile,  delimiter=',',skip_header=1, usecols=(1))
np.nanmax(data) # Use nanmax here in case there is a nan in the data

31956.465